### ISSUE TITLE
Unable to detect the angular app

### ISSUE THREAD

**Issue by opavader** [rajexcited/AngularJS-Birbal#1]
Getting the following error on console 

```
angularinspector.js:43 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': An object could not be cloned.
    at broadcastMessage (chrome-extension://lpgcgfldhlpcekibknamgefpbifakkai/src/content-script/inject/angularinspector.js:43:16)
    at sendDependencyTree (chrome-extension://lpgcgfldhlpcekibknamgefpbifakkai/src/content-script/inject/angularinspector.js:783:9)
    at inspectAngular (chrome-extension://lpgcgfldhlpcekibknamgefpbifakkai/src/content-script/inject/angularinspector.js:831:13)broadcastMessage @ angularinspector.js:43sendDependencyTree @ angularinspector.js:783inspectAngular @ angularinspector.js:831
```

the app is built with angular 1.5.6

**Comment by rajexcited** [comment]
There should not be an issue with new angular version.   I have run the example with angular 1.5.9, yet I haven't seen any issue such.  If you have a link or example plunker having this issue, I can take a look and help you.

**Comment by rajexcited** [comment]
I have added better error reporting  to upgraded of birbal extension in v0.0.8.

**Comment by opavader** [comment]
The extension is working now though console still has some errors on starting the performance analysis but metrics are being reported.

Error text : 
``` javascript
angular.js:14199 TypeError: Cannot read property 'length' of undefined
    at addedWatcher.get (<anonymous>:1:5681)
    at addedWatcher.get (<anonymous>:1:5622)
    at Scope.$digest (angular.js:17828)
    at Scope.scopePrototype.$digest (<anonymous>:1:6877)
    at Scope.$apply (angular.js:18102)
    at Scope.scopePrototype.$apply (<anonymous>:1:7521)
    at done (angular.js:12082)
    at completeRequest (angular.js:12291)
    at XMLHttpRequest.requestLoaded (angular.js:12219)
```

screenshots of console & Birbal dashboard 

![screen shot 2017-01-16 at 10 55 15 pm](https://cloud.githubusercontent.com/assets/14859766/21993057/f32ad144-dc3e-11e6-9904-1440fed2a397.png)
![screen shot 2017-01-16 at 10 56 27 pm](https://cloud.githubusercontent.com/assets/14859766/21993090/1b512ab0-dc3f-11e6-8edf-fc0b40e05085.png)
